name: Deploy via SFTP and rsync

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Set up SSH for Xserver
        run: |
          # ~/.sshディレクトリを作成
          mkdir -p ~/.ssh

          # 秘密鍵を保存
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_xserver_rsa

          # パーミッションの設定
          chmod 600 ~/.ssh/id_xserver_rsa

          # known_hostsにホスト情報を追加
          ssh-keyscan -p 10022 ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts

          # known_hostsのパーミッションを設定
          chmod 600 ~/.ssh/known_hosts

      - name: SSH and check directory
        run: |
          # SSHで接続してディレクトリを確認
          ssh -i ~/.ssh/id_xserver_rsa -p 10022 -o StrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} "pwd"
        env:
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_HOST: ${{ secrets.SFTP_HOST }}

      - name: Sync files with rsync
        run: |
          # rsyncでファイルを同期
          rsync -avz --delete -e "ssh -p 10022 -o StrictHostKeyChecking=no" ./out/ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/saki118.xsrv.jp/public_html
        env:
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
